component_depth: 1
languages:
- java
exclude:
- ./WCTCore/.*
- ./WCTCore/WebRoot/.*
- ./WCTCore/WebRoot/META-INF/.*
- ./WCTCore/WebRoot/WEB-INF/.*
- ./WCTCore/WebRoot/WEB-INF/lib/.*
- ./WCTCore/WebRoot/WEB-INF/tags/.*
- ./WCTCore/WebRoot/help/.*
- ./WCTCore/WebRoot/images/.*
- ./WCTCore/WebRoot/jsp/.*
- ./WCTCore/WebRoot/jsp/include/.*
- ./WCTCore/WebRoot/jsp/layouts/.*
- ./WCTCore/WebRoot/replay/.*
- ./WCTCore/WebRoot/scripts/.*
- ./WCTCore/WebRoot/styles/.*
- ./WCTCore/build/.*
- ./WCTCore/cfg/.*
- ./WCTCore/db/.*
- ./WCTCore/docs/.*
- ./WCTCore/docs/javadoc/.*
- ./WCTCore/docs/javadoc/org/.*
- ./WCTCore/docs/javadoc/org/archive/.*
- ./WCTCore/docs/javadoc/org/archive/crawler/.*
- ./WCTCore/docs/javadoc/org/archive/crawler/postprocessor/.*
- ./WCTCore/docs/javadoc/org/archive/io/.*
- ./WCTCore/docs/javadoc/org/webcurator/.*
- ./WCTCore/docs/javadoc/org/webcurator/auth/.*
- ./WCTCore/docs/javadoc/org/webcurator/auth/dbms/.*
- ./WCTCore/docs/javadoc/org/webcurator/auth/ldap/.*
- ./WCTCore/docs/javadoc/org/webcurator/auth/tag/.*
- ./WCTCore/docs/javadoc/org/webcurator/bl/.*
- ./WCTCore/docs/javadoc/org/webcurator/core/.*
- ./WCTCore/docs/javadoc/org/webcurator/core/admin/.*
- ./WCTCore/docs/javadoc/org/webcurator/core/agency/.*
- ./WCTCore/docs/javadoc/org/webcurator/core/archive/.*
- ./WCTCore/docs/javadoc/org/webcurator/core/archive/dps/.*
- ./WCTCore/docs/javadoc/org/webcurator/core/archive/file/.*
- ./WCTCore/docs/javadoc/org/webcurator/core/archive/oms/.*
- ./WCTCore/docs/javadoc/org/webcurator/core/check/.*
- ./WCTCore/docs/javadoc/org/webcurator/core/common/.*
- ./WCTCore/docs/javadoc/org/webcurator/core/exceptions/.*
- ./WCTCore/docs/javadoc/org/webcurator/core/harvester/.*
- ./WCTCore/docs/javadoc/org/webcurator/core/harvester/agent/.*
- ./WCTCore/docs/javadoc/org/webcurator/core/harvester/agent/exception/.*
- ./WCTCore/docs/javadoc/org/webcurator/core/harvester/agent/schedule/.*
- ./WCTCore/docs/javadoc/org/webcurator/core/harvester/coordinator/.*
- ./WCTCore/docs/javadoc/org/webcurator/core/harvester/util/.*
- ./WCTCore/docs/javadoc/org/webcurator/core/model/.*
- ./WCTCore/docs/javadoc/org/webcurator/core/notification/.*
- ./WCTCore/docs/javadoc/org/webcurator/core/permissionmapping/.*
- ./WCTCore/docs/javadoc/org/webcurator/core/profiles/.*
- ./WCTCore/docs/javadoc/org/webcurator/core/reader/.*
- ./WCTCore/docs/javadoc/org/webcurator/core/report/.*
- ./WCTCore/docs/javadoc/org/webcurator/core/report/dto/.*
- ./WCTCore/docs/javadoc/org/webcurator/core/report/impl/.*
- ./WCTCore/docs/javadoc/org/webcurator/core/report/parameter/.*
- ./WCTCore/docs/javadoc/org/webcurator/core/scheduler/.*
- ./WCTCore/docs/javadoc/org/webcurator/core/sites/.*
- ./WCTCore/docs/javadoc/org/webcurator/core/startup/.*
- ./WCTCore/docs/javadoc/org/webcurator/core/store/.*
- ./WCTCore/docs/javadoc/org/webcurator/core/store/arc/.*
- ./WCTCore/docs/javadoc/org/webcurator/core/store/tools/.*
- ./WCTCore/docs/javadoc/org/webcurator/core/store/tools/tree/.*
- ./WCTCore/docs/javadoc/org/webcurator/core/targets/.*
- ./WCTCore/docs/javadoc/org/webcurator/core/util/.*
- ./WCTCore/docs/javadoc/org/webcurator/domain/.*
- ./WCTCore/docs/javadoc/org/webcurator/domain/model/.*
- ./WCTCore/docs/javadoc/org/webcurator/domain/model/audit/.*
- ./WCTCore/docs/javadoc/org/webcurator/domain/model/auth/.*
- ./WCTCore/docs/javadoc/org/webcurator/domain/model/core/.*
- ./WCTCore/docs/javadoc/org/webcurator/domain/model/core/harvester/.*
- ./WCTCore/docs/javadoc/org/webcurator/domain/model/core/harvester/agent/.*
- ./WCTCore/docs/javadoc/org/webcurator/domain/model/dto/.*
- ./WCTCore/docs/javadoc/org/webcurator/domain/model/report/.*
- ./WCTCore/docs/javadoc/org/webcurator/ui/.*
- ./WCTCore/docs/javadoc/org/webcurator/ui/admin/.*
- ./WCTCore/docs/javadoc/org/webcurator/ui/admin/command/.*
- ./WCTCore/docs/javadoc/org/webcurator/ui/admin/controller/.*
- ./WCTCore/docs/javadoc/org/webcurator/ui/admin/validator/.*
- ./WCTCore/docs/javadoc/org/webcurator/ui/agent/.*
- ./WCTCore/docs/javadoc/org/webcurator/ui/agent/command/.*
- ./WCTCore/docs/javadoc/org/webcurator/ui/agent/controller/.*
- ./WCTCore/docs/javadoc/org/webcurator/ui/agent/validator/.*
- ./WCTCore/docs/javadoc/org/webcurator/ui/archive/.*
- ./WCTCore/docs/javadoc/org/webcurator/ui/base/.*
- ./WCTCore/docs/javadoc/org/webcurator/ui/common/.*
- ./WCTCore/docs/javadoc/org/webcurator/ui/common/editor/.*
- ./WCTCore/docs/javadoc/org/webcurator/ui/common/taglib/.*
- ./WCTCore/docs/javadoc/org/webcurator/ui/common/validation/.*
- ./WCTCore/docs/javadoc/org/webcurator/ui/credentials/.*
- ./WCTCore/docs/javadoc/org/webcurator/ui/credentials/command/.*
- ./WCTCore/docs/javadoc/org/webcurator/ui/credentials/controller/.*
- ./WCTCore/docs/javadoc/org/webcurator/ui/credentials/validator/.*
- ./WCTCore/docs/javadoc/org/webcurator/ui/groups/.*
- ./WCTCore/docs/javadoc/org/webcurator/ui/groups/command/.*
- ./WCTCore/docs/javadoc/org/webcurator/ui/groups/controller/.*
- ./WCTCore/docs/javadoc/org/webcurator/ui/groups/validator/.*
- ./WCTCore/docs/javadoc/org/webcurator/ui/home/.*
- ./WCTCore/docs/javadoc/org/webcurator/ui/home/controller/.*
- ./WCTCore/docs/javadoc/org/webcurator/ui/intray/.*
- ./WCTCore/docs/javadoc/org/webcurator/ui/intray/command/.*
- ./WCTCore/docs/javadoc/org/webcurator/ui/intray/controller/.*
- ./WCTCore/docs/javadoc/org/webcurator/ui/listener/.*
- ./WCTCore/docs/javadoc/org/webcurator/ui/management/.*
- ./WCTCore/docs/javadoc/org/webcurator/ui/management/command/.*
- ./WCTCore/docs/javadoc/org/webcurator/ui/management/controller/.*
- ./WCTCore/docs/javadoc/org/webcurator/ui/profiles/.*
- ./WCTCore/docs/javadoc/org/webcurator/ui/profiles/command/.*
- ./WCTCore/docs/javadoc/org/webcurator/ui/profiles/controller/.*
- ./WCTCore/docs/javadoc/org/webcurator/ui/profiles/renderers/.*
- ./WCTCore/docs/javadoc/org/webcurator/ui/profiles/validator/.*
- ./WCTCore/docs/javadoc/org/webcurator/ui/report/.*
- ./WCTCore/docs/javadoc/org/webcurator/ui/report/command/.*
- ./WCTCore/docs/javadoc/org/webcurator/ui/report/controller/.*
- ./WCTCore/docs/javadoc/org/webcurator/ui/report/validator/.*
- ./WCTCore/docs/javadoc/org/webcurator/ui/site/.*
- ./WCTCore/docs/javadoc/org/webcurator/ui/site/command/.*
- ./WCTCore/docs/javadoc/org/webcurator/ui/site/controller/.*
- ./WCTCore/docs/javadoc/org/webcurator/ui/site/editor/.*
- ./WCTCore/docs/javadoc/org/webcurator/ui/site/validator/.*
- ./WCTCore/docs/javadoc/org/webcurator/ui/target/.*
- ./WCTCore/docs/javadoc/org/webcurator/ui/target/command/.*
- ./WCTCore/docs/javadoc/org/webcurator/ui/target/controller/.*
- ./WCTCore/docs/javadoc/org/webcurator/ui/target/validator/.*
- ./WCTCore/docs/javadoc/org/webcurator/ui/tools/.*
- ./WCTCore/docs/javadoc/org/webcurator/ui/tools/command/.*
- ./WCTCore/docs/javadoc/org/webcurator/ui/tools/controller/.*
- ./WCTCore/docs/javadoc/org/webcurator/ui/tools/validator/.*
- ./WCTCore/docs/javadoc/org/webcurator/ui/util/.*
- ./WCTCore/etc/.*
- ./WCTDigitalAssetStore/.*
- ./WCTDigitalAssetStore/WebRoot/.*
- ./WCTDigitalAssetStore/WebRoot/META-INF/.*
- ./WCTDigitalAssetStore/WebRoot/WEB-INF/.*
- ./WCTDigitalAssetStore/WebRoot/WEB-INF/lib/.*
- ./WCTDigitalAssetStore/WebRoot/customDepositForms/.*
- ./WCTDigitalAssetStore/bin/.*
- ./WCTDigitalAssetStore/bin/org/.*
- ./WCTDigitalAssetStore/bin/org/webcurator/.*
- ./WCTDigitalAssetStore/bin/org/webcurator/core/.*
- ./WCTDigitalAssetStore/bin/org/webcurator/core/archive/.*
- ./WCTDigitalAssetStore/bin/org/webcurator/core/archive/dps/.*
- ./WCTDigitalAssetStore/bin/org/webcurator/core/archive/file/.*
- ./WCTDigitalAssetStore/bin/org/webcurator/core/archive/oms/.*
- ./WCTDigitalAssetStore/bin/org/webcurator/core/common/.*
- ./WCTDigitalAssetStore/bin/org/webcurator/core/startup/.*
- ./WCTDigitalAssetStore/bin/org/webcurator/core/store/.*
- ./WCTDigitalAssetStore/bin/org/webcurator/core/store/arc/.*
- ./WCTDigitalAssetStore/build/.*
- ./WCTDigitalAssetStore/cfg/.*
- ./WCTDigitalAssetStore/docs/.*
- ./WCTDigitalAssetStore/lib/.*
- ./WCTHarvestAgent/.*
- ./WCTHarvestAgent/WebRoot/.*
- ./WCTHarvestAgent/WebRoot/META-INF/.*
- ./WCTHarvestAgent/WebRoot/WEB-INF/.*
- ./WCTHarvestAgent/WebRoot/WEB-INF/lib/.*
- ./WCTHarvestAgent/bin/.*
- ./WCTHarvestAgent/bin/org/.*
- ./WCTHarvestAgent/bin/org/webcurator/.*
- ./WCTHarvestAgent/bin/org/webcurator/core/.*
- ./WCTHarvestAgent/bin/org/webcurator/core/check/.*
- ./WCTHarvestAgent/bin/org/webcurator/core/common/.*
- ./WCTHarvestAgent/bin/org/webcurator/core/harvester/.*
- ./WCTHarvestAgent/bin/org/webcurator/core/harvester/agent/.*
- ./WCTHarvestAgent/bin/org/webcurator/core/harvester/agent/exception/.*
- ./WCTHarvestAgent/bin/org/webcurator/core/harvester/agent/schedule/.*
- ./WCTHarvestAgent/bin/org/webcurator/core/harvester/coordinator/.*
- ./WCTHarvestAgent/bin/org/webcurator/core/harvester/util/.*
- ./WCTHarvestAgent/build/.*
- ./WCTHarvestAgent/cfg/.*
- ./WCTHarvestAgent/docs/.*
- ./WCTHarvestAgent/lib/.*
- ./WCTSubmitToRosetta/.*
- ./WCTSubmitToRosetta/build/.*
- ./WCTSubmitToRosetta/docs/.*
- ./WCTSubmitToRosetta/endorsed-lib/.*
- ./WCTSubmitToRosetta/lib/.*
- ./WCTSubmitToRosetta/lib/test-support/.*
- ./bin/.*
- ./bin/nz/.*
- ./bin/nz/govt/.*
- ./bin/nz/govt/natlib/.*
- ./bin/nz/govt/natlib/ndha/.*
- ./bin/nz/govt/natlib/ndha/common/.*
- ./bin/nz/govt/natlib/ndha/common/dublincore/.*
- ./bin/nz/govt/natlib/ndha/common/mets/.*
- ./bin/nz/govt/natlib/ndha/test/.*
- ./bin/nz/govt/natlib/ndha/wctdpsdepositor/.*
- ./bin/nz/govt/natlib/ndha/wctdpsdepositor/dpsdeposit/.*
- ./bin/nz/govt/natlib/ndha/wctdpsdepositor/dpsdeposit/dpsresult/.*
- ./bin/nz/govt/natlib/ndha/wctdpsdepositor/dpsdeposit/dspresult/.*
- ./bin/nz/govt/natlib/ndha/wctdpsdepositor/extractor/.*
- ./bin/nz/govt/natlib/ndha/wctdpsdepositor/extractor/filearchivebuilder/.*
- ./bin/nz/govt/natlib/ndha/wctdpsdepositor/extractor/filefinder/.*
- ./bin/nz/govt/natlib/ndha/wctdpsdepositor/filemover/.*
- ./bin/nz/govt/natlib/ndha/wctdpsdepositor/mets/.*
- ./bin/nz/govt/natlib/ndha/wctdpsdepositor/pds/.*
- ./bin/nz/govt/natlib/ndha/wctdpsdepositor/preprocessor/.*
- ./bin/org/.*
- ./bin/org/archive/.*
- ./bin/org/archive/crawler/.*
- ./bin/org/archive/crawler/postprocessor/.*
- ./bin/org/archive/io/.*
- ./bin/org/webcurator/.*
- ./bin/org/webcurator/auth/.*
- ./bin/org/webcurator/auth/dbms/.*
- ./bin/org/webcurator/auth/ldap/.*
- ./bin/org/webcurator/auth/tag/.*
- ./bin/org/webcurator/bl/.*
- ./bin/org/webcurator/core/.*
- ./bin/org/webcurator/core/admin/.*
- ./bin/org/webcurator/core/agency/.*
- ./bin/org/webcurator/core/archive/.*
- ./bin/org/webcurator/core/archive/dps/.*
- ./bin/org/webcurator/core/check/.*
- ./bin/org/webcurator/core/common/.*
- ./bin/org/webcurator/core/exceptions/.*
- ./bin/org/webcurator/core/harvester/.*
- ./bin/org/webcurator/core/harvester/agent/.*
- ./bin/org/webcurator/core/harvester/coordinator/.*
- ./bin/org/webcurator/core/model/.*
- ./bin/org/webcurator/core/notification/.*
- ./bin/org/webcurator/core/permissionmapping/.*
- ./bin/org/webcurator/core/profiles/.*
- ./bin/org/webcurator/core/reader/.*
- ./bin/org/webcurator/core/report/.*
- ./bin/org/webcurator/core/report/dto/.*
- ./bin/org/webcurator/core/report/impl/.*
- ./bin/org/webcurator/core/report/parameter/.*
- ./bin/org/webcurator/core/scheduler/.*
- ./bin/org/webcurator/core/sites/.*
- ./bin/org/webcurator/core/store/.*
- ./bin/org/webcurator/core/store/tools/.*
- ./bin/org/webcurator/core/store/tools/tree/.*
- ./bin/org/webcurator/core/targets/.*
- ./bin/org/webcurator/core/util/.*
- ./bin/org/webcurator/domain/.*
- ./bin/org/webcurator/domain/model/.*
- ./bin/org/webcurator/domain/model/audit/.*
- ./bin/org/webcurator/domain/model/auth/.*
- ./bin/org/webcurator/domain/model/core/.*
- ./bin/org/webcurator/domain/model/core/harvester/.*
- ./bin/org/webcurator/domain/model/core/harvester/agent/.*
- ./bin/org/webcurator/domain/model/dto/.*
- ./bin/org/webcurator/domain/model/report/.*
- ./bin/org/webcurator/ui/.*
- ./bin/org/webcurator/ui/admin/.*
- ./bin/org/webcurator/ui/admin/command/.*
- ./bin/org/webcurator/ui/admin/controller/.*
- ./bin/org/webcurator/ui/admin/validator/.*
- ./bin/org/webcurator/ui/agent/.*
- ./bin/org/webcurator/ui/agent/command/.*
- ./bin/org/webcurator/ui/agent/controller/.*
- ./bin/org/webcurator/ui/agent/validator/.*
- ./bin/org/webcurator/ui/archive/.*
- ./bin/org/webcurator/ui/base/.*
- ./bin/org/webcurator/ui/common/.*
- ./bin/org/webcurator/ui/common/editor/.*
- ./bin/org/webcurator/ui/common/taglib/.*
- ./bin/org/webcurator/ui/common/validation/.*
- ./bin/org/webcurator/ui/credentials/.*
- ./bin/org/webcurator/ui/credentials/command/.*
- ./bin/org/webcurator/ui/credentials/controller/.*
- ./bin/org/webcurator/ui/credentials/validator/.*
- ./bin/org/webcurator/ui/groups/.*
- ./bin/org/webcurator/ui/groups/command/.*
- ./bin/org/webcurator/ui/groups/controller/.*
- ./bin/org/webcurator/ui/groups/validator/.*
- ./bin/org/webcurator/ui/home/.*
- ./bin/org/webcurator/ui/home/controller/.*
- ./bin/org/webcurator/ui/intray/.*
- ./bin/org/webcurator/ui/intray/command/.*
- ./bin/org/webcurator/ui/intray/controller/.*
- ./bin/org/webcurator/ui/listener/.*
- ./bin/org/webcurator/ui/management/.*
- ./bin/org/webcurator/ui/management/command/.*
- ./bin/org/webcurator/ui/management/controller/.*
- ./bin/org/webcurator/ui/profiles/.*
- ./bin/org/webcurator/ui/profiles/command/.*
- ./bin/org/webcurator/ui/profiles/controller/.*
- ./bin/org/webcurator/ui/profiles/renderers/.*
- ./bin/org/webcurator/ui/profiles/validator/.*
- ./bin/org/webcurator/ui/report/.*
- ./bin/org/webcurator/ui/report/command/.*
- ./bin/org/webcurator/ui/report/controller/.*
- ./bin/org/webcurator/ui/report/validator/.*
- ./bin/org/webcurator/ui/site/.*
- ./bin/org/webcurator/ui/site/command/.*
- ./bin/org/webcurator/ui/site/controller/.*
- ./bin/org/webcurator/ui/site/editor/.*
- ./bin/org/webcurator/ui/site/validator/.*
- ./bin/org/webcurator/ui/target/.*
- ./bin/org/webcurator/ui/target/command/.*
- ./bin/org/webcurator/ui/target/controller/.*
- ./bin/org/webcurator/ui/target/validator/.*
- ./bin/org/webcurator/ui/tools/.*
- ./bin/org/webcurator/ui/tools/command/.*
- ./bin/org/webcurator/ui/tools/controller/.*
- ./bin/org/webcurator/ui/tools/validator/.*
- ./bin/org/webcurator/ui/util/.*
- ./lib/.*
